Title __ SETTLEMENT FILES GENERATOR - DEBENHAMS
:START
@Echo off
cls
color 3
Echo.
Echo ******** SETTLEMENT FILES GENERATOR **********
Echo.
GOTO START
:START
SET /P ENV=PLEASE ENTER ENVIRONMENT : 
Echo.
if {%ENV%}=={} GOTO START
IF %ENV%== alpha ( set DIR=CRDTSTD60 
GOTO FOLDER)
IF %ENV%== ALPHA ( set DIR=CRDTSTD60
GOTO FOLDER)
IF %ENV%== Alpha ( set DIR=CRDTSTD60
GOTO FOLDER)
IF %ENV%== Beta ( set DIR=CRDTSTD40
GOTO FOLDER)
IF %ENV%== beta ( set DIR=CRDTSTD40
GOTO FOLDER)
IF %ENV%== BETA ( set DIR=CRDTSTD40
GOTO FOLDER)
IF %ENV%== Gamma ( set DIR=CRDTSTD40
GOTO FOLDER)
IF %ENV%== gamma ( set DIR=CRDTSTD40
GOTO FOLDER)
IF %ENV%== GAMMA ( set DIR=CRDTSTD40
GOTO FOLDER)
IF %ENV%==delta ( set DIR=CRDTSTD70
GOTO FOLDER)
IF %ENV%== Delta ( set DIR=CRDTSTD70
GOTO FOLDER)
IF %ENV%== DELTA ( set DIR=CRDTSTD70
GOTO FOLDER)
IF %ENV%== epsilon ( set DIR=CRDTSTD80
GOTO FOLDER)
IF %ENV%== EPSILON ( set DIR=CRDTSTD80
GOTO FOLDER)
IF %ENV%== Epsilon ( set DIR=CRDTSTD80
GOTO FOLDER)

GOTO ERROR


:FOLDER
SET /P FOLDER=PLEASE ENTER DESTINATION FOLDER NAME (EG. C:\FILES): 
echo.
IF {%FOLDER%}=={} GOTO STEP2
IF NOT EXIST %FOLDER% ( Echo PATH %FOLDER% DOESNT EXIST. TRYING TO CREATE %FOLDER%....
mkDIR %FOLDER% )
echo.
IF NOT EXIST %FOLDER% ( Echo ERROR WHILE CREATING %FOLDER% !! PROCESS TERMINATING..
GOTO REPEAT)

:GENERATE
@echo open tn3 > $$ftp$$.txt
@echo REXMNT >> $$ftp$$.txt
@echo MONKEY >> $$ftp$$.txt
@echo cd %DIR% >> $$ftp$$.txt
@echo GET CRDPRIXP  %FOLDER%\CRDPRIXP.TXT >> $$ftp$$.txt
@echo GET CRDPRIDP  %FOLDER%\CRDPRIDP.TXT >> $$ftp$$.txt
@echo bye >> $$ftp$$.txt
ftp -i -s:$$ftp$$.txt
del $$ftp$$.txt
START %FOLDER%
exit

:ERROR
ECHO INVALID ENVIRONMENT NAME - %ENV% !! Valid = ALPHA, BETA, GAMMA, DELTA, EPSILON
GOTO REPEAT 

:REPEAT
Echo.
SET /P inp=ENTER "Y" TO START AGAIN OR ANY OTHER KEY TO EXIT. CONTINUE(Y/N)? 
IF %inp% == Y GOTO START
IF %inp% == y GOTO START
exit